[package]
name = "byond-tracy-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tracy-client = "0.18.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = ["Win32_System_LibraryLoader"] }
